#!/usr/bin/perl

use strict;
use LWP::UserAgent;
use File::Copy;

my $ua = LWP::UserAgent->new;

my @abbr = ("AL","AK","AS","AZ","AR","CA","CO","CT","DE","DC","FM","FL","GA","GU","HI","ID","IL","IN","IA","KS","KY","LA","ME","MH","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","MP","OH","OK","OR","PW","PA","PR","RI","SC","SD","TN","TX","UT","VT","VI","VA","WA","WV","WI","WY");

for (my $i=0;$i<scalar @abbr;$i++)
{
	print "$abbr[$i]\n";
}

while (1)
{
	print "in loop\n";
	my $res = $ua->get("http://localhost:3000/reports.kml?live=1&count=4000");
	my $content = $res->content;
	open(KML, ">reports.kml");
	print KML $content;
	close(KML);
	
	move("reports.kml", "public/feeds/4000.kml");
	
	for (my $i=0;$i<scalar @abbr;$i++)
	{
		print "Fetching $abbr[$i]\n";
		state($abbr[$i],$ua);
	}
	homepage($ua);
	
	sleep(60);
}

sub state
{
	my $state = shift;
	my $ua = shift;
	for (my $i=1;$i<=3;$i++)
	{
		open (STATE, ">$i.json");
		my $res = $ua->get("http://localhost:3000/reports.json?state=$state&wait_time=0&per_page=200&callback=updateJSON&page=$i");
		print STATE $res->content;
		close STATE;
		move("$i.json", "public/feeds/json/$state/$i.json");
	}
}

sub homepage
{
	my $ua = shift;
	for (my $i=1;$i<=20;$i++)
	{
		my $res = $ua->get("http://localhost:3000/reports.json?wait_time=0&per_page=200&callback=updateJSON&page=$i");
		my $content = $res->content;
		open(JSON, ">$i.json");
		print JSON $content;
		close(JSON);
		move("$i.json", "public/feeds/$i.json");
	}
}